# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gymplan', '0002_auto_20170817_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPerformed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.SmallIntegerField()),
                ('variableIsReps', models.BooleanField(default=False)),
                ('numberPerformed', models.SmallIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymplan.UserExercises')),
            ],
            options={
                'verbose_name': "User's Reps Data",
                'verbose_name_plural': "User's Reps Data",
            },
        ),
    ]
