# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperformed',
            name='performedWithDumbbells',
            field=models.BooleanField(default=True),
        ),
    ]
