# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymtracker', '0002_userperformed_performedwithdumbbells'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userperformed',
            name='performedWithDumbbells',
        ),
    ]
