# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseMuscleGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Exercise Target Muscle',
                'verbose_name_plural': 'Exercise Target Muscles',
            },
        ),
        migrations.CreateModel(
            name='ExerciseName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exerciseName', models.CharField(max_length=50, unique=True)),
                ('isApproved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Exercise/Movement',
                'verbose_name_plural': 'Exercises/Movements',
            },
        ),
        migrations.CreateModel(
            name='ExerciseTips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exerciseTip', models.CharField(max_length=200, unique=True)),
                ('exerciseName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.ExerciseName')),
            ],
            options={
                'verbose_name': 'Exercise Tip',
                'verbose_name_plural': 'Exercise Tips',
            },
        ),
        migrations.CreateModel(
            name='MacroBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macroDesc', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Macro Body Part',
                'verbose_name_plural': 'Macro Body Parts',
            },
        ),
        migrations.CreateModel(
            name='MicroBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microDesc', models.CharField(max_length=50, unique=True)),
                ('macroBody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.MacroBody')),
            ],
            options={
                'verbose_name': 'Micro Body Part',
                'verbose_name_plural': 'Micro Body Parts',
            },
        ),
        migrations.AddField(
            model_name='exercisemusclegroups',
            name='exerciseName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.ExerciseName'),
        ),
        migrations.AddField(
            model_name='exercisemusclegroups',
            name='targetMacro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.MacroBody', unique=True),
        ),
        migrations.AddField(
            model_name='exercisemusclegroups',
            name='targetMicro',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.MicroBody', unique=True),
        ),
    ]
