# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 17:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.ExerciseName')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "User's Exercise",
                'verbose_name_plural': "User's Exercises",
            },
        ),
        migrations.CreateModel(
            name='UserExercisesSetReps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.SmallIntegerField()),
                ('userExercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymplan.UserExercises')),
            ],
            options={
                'verbose_name': "User's Exercise Reps",
                'verbose_name_plural': "User's Exercises Reps",
            },
        ),
    ]
