# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 20:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gymplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "User's Exercise Group Name",
                'verbose_name_plural': "User's Exercise Group Name",
            },
        ),
        migrations.CreateModel(
            name='ExerciseGroupSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosenDays', models.DateField()),
                ('exerciseGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymplan.ExerciseGroup')),
            ],
            options={
                'verbose_name': 'Exercise Group Days',
                'verbose_name_plural': "User's Exercises in Group",
            },
        ),
        migrations.CreateModel(
            name='ExercisesInGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymplan.UserExercises')),
                ('groupName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymplan.ExerciseGroup')),
            ],
            options={
                'verbose_name': "User's Exercises in Group",
                'verbose_name_plural': "User's Exercises in Group",
            },
        ),
        migrations.CreateModel(
            name='UserExerciseTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFixedReps', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "User's Template",
                'verbose_name_plural': "User's Templates",
            },
        ),
        migrations.RenameField(
            model_name='userexercisessetreps',
            old_name='reps',
            new_name='sets',
        ),
    ]
