# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymplan', '0002_auto_20170817_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexercises',
            name='performedWith',
            field=models.CharField(choices=[('M', 'Machines'), ('D', 'Dumbbells'), ('B', 'Barbell')], default='D', max_length=1),
        ),
    ]
