# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymplan', '0003_userexercises_performedwith'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisegroupschedule',
            options={'verbose_name': "User's Exercise Group Schedule", 'verbose_name_plural': "User's Exercises Group Schedule"},
        ),
    ]
