# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymplan', '0004_auto_20170817_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexercises',
            name='performedWith',
            field=models.CharField(choices=[('M', 'Machines'), ('D', 'Dumbbells'), ('B', 'Barbell'), ('C', 'Cable')], default='D', max_length=1),
        ),
    ]
