# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gymplan', '0005_auto_20170817_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisesInSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymplan.UserExercises')),
            ],
            options={
                'verbose_name': "User's Exercises in Session",
                'verbose_name_plural': "User's Exercises in Session",
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionName', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "User's Exercise Session",
                'verbose_name_plural': "User's Exercise Session",
            },
        ),
        migrations.RemoveField(
            model_name='exercisegroup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exercisesingroup',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exercisesingroup',
            name='groupName',
        ),
        migrations.RemoveField(
            model_name='exercisegroupschedule',
            name='exerciseGroup',
        ),
        migrations.DeleteModel(
            name='ExerciseGroup',
        ),
        migrations.DeleteModel(
            name='ExercisesInGroup',
        ),
        migrations.AddField(
            model_name='exercisesinsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymplan.Session'),
        ),
        migrations.AddField(
            model_name='exercisegroupschedule',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gymplan.Session'),
            preserve_default=False,
        ),
    ]
