# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymplan', '0007_auto_20170820_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexercisessetreps',
            old_name='sets',
            new_name='reps',
        ),
        migrations.AddField(
            model_name='userexercisessetreps',
            name='setNumber',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
